#
# Copyright (C) 2017 Xue Liu <liuxuenetmail@gmail.com>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Semtech LoraWAN Gateway Configuration
#LUCI_DEPENDS:=

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature